const { test, expect } = require('@playwright/test');
const { loginBrowser, loginRequest } = require('./auth.cjs');

test('password-free profile selection preserves user permissions and supports switching roles', async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('rsvroom.user', '60000000-0000-4000-8000-000000000001');localStorage.setItem('rsvroom.language', 'en'); });
  await page.goto('/');
  await expect(page.locator('input[type=password]')).toHaveCount(0);
  await page.getByRole('combobox',{name:'Employee',exact:true}).locator('..').click();
  await page.getByRole('option',{name:'Ola Example · User',exact:true}).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Make room for a good day.' })).toBeVisible();
  for (const name of ['Administration', 'Plan editor', 'People']) await expect(page.getByRole('button', { name, exact: true })).toHaveCount(0);
  await page.goto('/#admin');
  await expect(page.getByRole('heading', { name: 'Access denied', exact: true })).toBeVisible();
  await page.goto('/#floor-editor/40000000-0000-4000-8000-000000000001');
  await expect(page.getByRole('heading', { name: 'Access denied', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Ola Example', exact: true }).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('combobox',{name:'Employee',exact:true}).locator('..').click();
  await page.getByRole('option',{name:'Anna Example · Administrator',exact:true}).click();
  await dialog.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(page.getByRole('button',{name:'Administration',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Anna Example',exact:true}).click();
  await page.getByRole('dialog').getByRole('combobox',{name:'Employee',exact:true}).locator('..').click();
  await page.getByRole('option',{name:'Max Example · Key user',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();
  await expect(page.getByRole('button',{name:'People',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Administration',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Plan editor',exact:true})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('button',{name:'Max Example',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Max Example',exact:true}).click();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Choose your profile', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Language', exact: true }).press('Space');
  await page.getByRole('option', { name: 'German', exact: true }).click();
  await page.getByRole('combobox',{name:'Mitarbeiter',exact:true}).locator('..').click();
  await expect(page.getByRole('option',{name:'Max Example · Schlüsselbenutzer',exact:true})).toBeVisible();
});

test('key users add regular accounts without access to Administration', async ({ page, request }) => {
  await loginBrowser(page, request, 'max@example.de');
  await page.goto('/#users');
  await expect(page.getByRole('button', { name: 'Administration', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Add user', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Name', { exact: true }).fill('Browser role user');
  await dialog.getByLabel('Email', { exact: true }).fill('browser-role@example.com');
  await expect(dialog.locator('.sapMSltDisabled').filter({ hasText: 'User' })).toBeVisible();
  await expect(dialog.locator('input[type=password]')).toHaveCount(0);
  await dialog.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Browser role user', exact: true })).toBeVisible();
  const added = (await (await request.get('/odata/v4/booking/Users')).json()).value.find(row => row.email === 'browser-role@example.com');
  expect(added.role).toBe('USER');
  await loginRequest(request,added.email);
  await loginRequest(request,'anna@example.com');
  expect((await request.delete(`/odata/v4/booking/Users(${added.ID})`)).status()).toBe(204);
});

test('key users can delete foreign bookings, and administrators can change roles', async ({ page, request }) => {
  await loginRequest(request,'ola@example.com');
  const response = await request.post('/odata/v4/booking/Bookings', { data: { resource_ID: '50000000-0000-4000-8000-000000000001', user_ID: '60000000-0000-4000-8000-000000000003', title: 'Foreign booking for role test', startAt: '2042-03-01T09:00:00Z', endAt: '2042-03-01T10:00:00Z' } });
  expect(response.ok(), await response.text()).toBe(true);
  await loginBrowser(page, request, 'max@example.de');
  await page.goto('/#bookings');
  await page.getByRole('option', { name: 'All bookings', exact: true }).click();
  const card = page.locator('.bookingCard').filter({ hasText: 'Foreign booking for role test' });
  await expect(card.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(0);
  await card.getByRole('button', { name: 'Delete booking', exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'OK', exact: true }).click();
  await expect(card).toHaveCount(0);
  await loginBrowser(page, request);
  await page.goto('/admin');
  await expect(page.getByRole('heading', { name: 'Administration', exact: true })).toBeVisible();
  await page.locator('.adminToolbar').getByRole('combobox').press('Space');
  await page.getByRole('option', { name: 'People', exact: true }).click();
  const userRow = page.getByRole('row').filter({ hasText: 'Ola Example' });
  await userRow.getByRole('button', { name: 'Edit', exact: true }).click();
  const roles = page.getByRole('dialog').getByRole('combobox', { name: 'Role', exact: true });
  await expect(roles).not.toHaveAttribute('aria-disabled', 'true');
  await roles.locator('..').click();
  await page.getByRole('option', { name: 'Key user', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Save changes', exact: true }).click();
  const endpoint='/odata/v4/booking/Users(60000000-0000-4000-8000-000000000003)';
  await expect.poll(async () => (await (await request.get(endpoint)).json()).role).toBe('KEY_USER');
  expect((await request.patch(endpoint,{data:{role:'USER'}})).ok()).toBe(true);
});
